version: 0.2

      phases: 
          install:
              runtime-versions: 14.16.1
                  nodejs: 
              commands:
                  - echo Entering install phase...
                  - npx lerna bootstrap
          pre_build:
              commands: 
                  - echo Entering pre_build phase... 
                  - npx lerna run lint
          build: 
              commands:
                  - echo Entering build phase...
                  - npx lerna run build
                  - npx lerna run test
                  - ./deploy.sh
                  - npx lerna clean --yes