version: 0.2

      phases: 
          install:
              runtime-versions: 
                  nodejs: 12
              commands:
                  - echo "Entering install phase..."
                  - npx lerna run lint
                  - npx lerna bootstrap
                  - chmod +x scripts/install.sh; scripts/install.sh
          pre_build:
              commands: 
                  - echo "Entering pre_build phase..."
                  - chmod +x scripts/pm2.sh; scripts/pm2.sh
                  - npx lerna run test
          build: 
              commands:
                  - echo "Entering build phase..."
                  - chmod +x scripts/aws_config.sh; scripts/aws_config.sh
                  - chmod +x scripts/build.sh; scripts/build.sh
                  - chmod +x scripts/deploy.sh; scripts/deploy.sh
                  - npx lerna clean --y