version: 0.2

      phases: 
          install:
              runtime-versions: 
                  nodejs: 12
              commands:
                  - echo "Entering install phase..."
                  - npx lerna run lint 
                  - zip Infra/lambda.zip Infra/index.js  # overwrite Infra/lambda.zip with Infra/index.js
                  - npx lerna bootstrap
                  - chmod -R 555 scripts
                  - scripts/install.sh
          pre_build:
              commands: 
                  - echo "Entering pre_build phase..."
                  - scripts/pm2.sh
                  - npx lerna run test #  npm run test
                  - sudo pm2 stop all
          build: 
              commands:
                  - echo "Entering build phase..."
                  - scripts/aws_config.sh
                  - scripts/build.sh
                  - scripts/test.sh 
                  - scripts/deploy.sh
                  - npx lerna clean --y # optional